apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-deployment
  name: db-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment-pod
  template:
    metadata:
      labels:
        app: db-deployment-pod
    spec:
      volumes:
      - name: db-data
        emptyDir: {}
      containers:
      - image: postgres:9.4
        name: postgres
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data

