apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-pod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker-pod
    spec:
      containers:
      - image: kodekloud/examplevotingapp_worker
        name: worker-container



